### ISSUE TITLE
Update master branch

### ISSUE THREAD

**Issue by conklech** [simoncozens/libtexpdf#5]
The branch `master` appears to be lagging a few years behind the "branch" being followed by sile, which currently depends on 4ce3da6. Because 4ce3da6 and friends are not on any (public) branch, it's awkward to follow the project on Github and elsewhere, and difficult to track future updates.

Would it be appropriate to bump master up to 4ce3da6?

**Comment by alerque** [comment]
This appears to have been dealt with, the issue can be closed.
